language: ruby

script: bundle exec rake travis

bundler_args: --without development

rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - gem update bundler

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: ruby-head
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2b123a7c09134ded59f
    on_success: alawys
    on_failure: always
    on_start: always

env:
  global:
    - secure: V4GY43nbctCpHtWmLu3n12+vhiKi2k1LebQ9EwfcAWzL6MlkS85Dn5B7ozNnKb+Zg19/5Vqd8BFIcuxoif7PizTyT+Xz3UgR81WbYTINbahRqnixR6tq+fzy2mqhyB6gmVDGysepVmNvN0aMbPuXIz3O0pzQHpdVVdDiQxDNcpQ=
    - secure: pI4xVJ1qPH25E2m9RNcpp/TWIrM1v0sohohWUSZBzjiOgGh9pXrcXAI/Rsm26R2oyZuPDEwhdyP0Tw7JmD9f3ArNpLDZsFvatJltQwrdQasNU0cCQM0CfNlkSMaGf0nN1T8MU2CBCSJj8DQnELsw2dQjmVKnkPM/D4bRUKkI4gQ=
